#!/bin/bash

usage () { echo "Usage: $0 [-c <critical threshold>] [-w <warning threshold>] [-e <email address>]" 1>&2; exit 1;}

while getopts ":c:w:e:" opt; do
  case $opt in
    c)
      crTh="$OPTARG"
      ;;
    w)
      waTh="$OPTARG"
      ;;
    e)
      emAd="$OPTARG"
      ;;
    *)
      echo "Requires a parameter" 
      usage
      ;;
  esac
done
shift $((OPTIND-1))
if [[ ! -z $crTh && ! -z $waTh && ! -z $emAd ]]; then
  echo $crTh
  echo $waTh
  echo $emAd
fi
if [ -z "${crTh}" ] || [ -z "${wrTh}"] || [ -z "${emAd}"]; then
  usage
fi
