#!/bin/bash

usage () { echo "Usage: $0 [-c <critical threshold>] [-w <warning threshold>] [-e <email address>]" 1>&2; exit 1;}

while getopts ":cwe" opt; do
  case $opt in
    c)
      echo "critical threshold"
      ;;
    w)
      echo "warning threshold"
      ;;
    e)
      echo "email@address.com"
      ;;
    *)
      echo "Requires a parameter" >&2
      usage
      ;;
  esac
done
shift $((OPTIND-1))
if [ -z "${s}" ] || [ -z "${w}"] || [ -z "$(e)"]; then
  usage
fi
