#!/bin/bash

usage () 
{ 
  echo "Usage: $0 [-c <critical threshold (percentage)>] [-w <warning threshold (percentage)>] [-e <email address to send the report>]" ;
  exit;
}
mem_check()
{
  USED_MEMORY=$( free | grep Mem: | awk '{print $3/2 *100.0}');
  if [[ $USED_MEMORY -ge $crTh && $USED_MEMORY -lt 100 ]]; then
    echo "2";
  else
  if [[ $USED_MEMORY -ge $waTh && $USED_MEMORY -lt $crTh ]]; then
    echo "1"
  else
  if [[ $USED_MEMORY -lt $waTh && $USED_MEMORY -ge 0 ]]; then
    echo "0";
  fi
  fi
  fi
  exit;
}
validation()
{
  echo "Percentage of critical threshold must be greater than warning threshold";
}
while getopts ":c:w:e:" opt; do
  case $opt in
    c)
      crTh="$OPTARG"
      ;;
    w)
      waTh="$OPTARG"
      ;;
    e)
      emAd="$OPTARG"
      ;;
    *)
      echo "Requires a parameter" 
      usage
      ;;
  esac
done

if [[ ! -z $crTh && ! -z $waTh && ! -z $emAd ]]; then
  if [ $crTh -ge $waTh ]; then
    mem_check
  else
    validation
    usage
  fi
fi

if [ -z "${crTh}" ] || [ -z "${wrTh}"] || [ -z "${emAd}"]; then
  usage
fi

shift $((OPTIND-1))
